# Generated by Django 4.1.5 on 2023-01-12 19:35

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('mini_githubcic', '0002_issue_is_open_issue_project_pullrequest_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='state',
        ),
        migrations.AddField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mini_githubcic.branch'),
        ),
        migrations.AddField(
            model_name='commit',
            name='branches',
            field=models.ManyToManyField(default=None, related_name='branches', to='mini_githubcic.branch'),
        ),
        migrations.AddField(
            model_name='commit',
            name='parents',
            field=models.ManyToManyField(blank=True, to='mini_githubcic.commit'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
