# Generated by Django 4.1.5 on 2023-01-08 14:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0002_issue_is_open_issue_project_pullrequest_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
