# Generated by Django 3.2.16 on 2023-01-10 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0003_milestone_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
