# Generated by Django 4.1.5 on 2023-01-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0003_remove_commit_branch_remove_milestone_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='parents',
            field=models.ManyToManyField(blank=True, to='mini_githubcic.commit', verbose_name='Parent commits'),
        ),
    ]
