# Generated by Django 3.2.16 on 2023-01-12 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0003_alter_label_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='state',
        ),
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project'),
        ),
    ]
