# Generated by Django 3.2.16 on 2023-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0004_milestone_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='state',
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
