# Generated by Django 4.1.5 on 2023-01-23 15:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0004_alter_commit_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorfield.fields.ColorField(default='#00000', image_field=None, max_length=18, samples=None),
        ),
    ]
