# Generated by Django 3.2.16 on 2023-01-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0004_auto_20230112_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mini_githubcic.branch'),
        ),
        migrations.AddField(
            model_name='commit',
            name='branches',
            field=models.ManyToManyField(default=None, related_name='branches', to='mini_githubcic.Branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
