# Generated by Django 3.2.16 on 2023-01-18 13:50

import colorfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0004_alter_commit_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='watched',
            field=models.ManyToManyField(related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorfield.fields.ColorField(default='#00000', image_field=None, max_length=18, samples=None),
        ),
    ]
