# Generated by Django 4.1.5 on 2023-01-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0005_remove_issue_project_task_project_alter_label_color'),
        ('mini_githubcic', '0005_user_access_token_alter_label_color'),
    ]

    operations = [
    ]
