# Generated by Django 3.2.16 on 2023-01-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0003_alter_label_color'),
        ('mini_githubcic', '0005_auto_20230111_1047'),
    ]

    operations = [
    ]
