# Generated by Django 4.1.5 on 2023-01-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0003_alter_label_color'),
        ('mini_githubcic', '0005_auto_20230111_1047'),
    ]

    operations = [
    ]
