# Generated by Django 3.2.16 on 2023-01-18 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0005_auto_20230118_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reded', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=50)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
