# Generated by Django 3.2.16 on 2023-01-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0006_merge_0003_alter_label_color_0005_auto_20230111_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='watched',
            field=models.ManyToManyField(related_name='watched', to='mini_githubcic.User'),
        ),
    ]
