# Generated by Django 4.1.5 on 2023-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0006_merge_0003_alter_label_color_0005_auto_20230111_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, to='mini_githubcic.commit'),
        ),
    ]
