# Generated by Django 3.2.16 on 2023-01-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fork_parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='forked_project',
            field=models.ManyToManyField(default=None, related_name='_mini_githubcic_project_forked_project_+', to='mini_githubcic.Project'),
        ),
    ]
