# Generated by Django 3.2.16 on 2023-01-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0008_task_labels_alter_user_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fork_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_forked_project',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='watched',
            field=models.ManyToManyField(related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reded', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=50)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
