# Generated by Django 4.1.4 on 2023-01-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0008_alter_user_managers_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
