# Generated by Django 3.2.16 on 2023-01-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0008_auto_20230119_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fork_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='forked_project',
            field=models.ManyToManyField(null=True, related_name='_mini_githubcic_project_forked_project_+', to='mini_githubcic.Project'),
        ),
    ]
