# Generated by Django 4.1.5 on 2023-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0008_task_labels_alter_user_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_message',
            field=models.CharField(default='empty_event', max_length=255),
        ),
    ]
