# Generated by Django 4.1.5 on 2023-01-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0009_event_event_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mini_githubcic.event')),
                ('created_entity_type', models.CharField(max_length=20)),
            ],
            bases=('mini_githubcic.event',),
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_message',
        ),
    ]
