# Generated by Django 4.1.4 on 2023-01-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0010_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
