# Generated by Django 3.2.16 on 2023-01-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0010_auto_20230119_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='forked_project',
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_forked_project',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
