# Generated by Django 4.1.5 on 2023-01-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0011_remove_comment_writer_event_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateChange',
        ),
    ]
