# Generated by Django 3.2.16 on 2023-01-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0011_auto_20230119_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fork_parent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='number_of_forked_project',
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_forked_project', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('fork_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forked_project', to='mini_githubcic.project')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project')),
            ],
        ),
    ]
