# Generated by Django 3.2.16 on 2023-01-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0012_auto_20230119_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fork_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_githubcic.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_forked_project',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
