# Generated by Django 4.1.5 on 2023-01-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0012_delete_statechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelapplication',
            old_name='label',
            new_name='applied_labels',
        ),
    ]
