# Generated by Django 4.1.5 on 2023-01-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0009_auto_20230125_0958'),
        ('mini_githubcic', '0013_rename_label_labelapplication_applied_labels'),
    ]

    operations = [
    ]
