# Generated by Django 3.2.16 on 2023-01-29 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_githubcic', '0014_merge_20230125_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to='mini_githubcic.task'),
        ),
    ]
