name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-vllersion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd mini_githubcic
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Django DB
      run: |
        cd mini_githubcic
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Django Test Suite
      run: |
        cd mini_githubcic
        python manage.py test mini_githubcic.test --noinput